language: python
python:
  - "3.9"
  - "3.10"
  - "3.11"
env:
  - DJANGO_VERSION=3.2.23
  - DJANGO_VERSION=4.1.13
  - DJANGO_VERSION=4.2.8
script: "python manage.py test batchform"
install:
  - pip install Django==$DJANGO_VERSION --quiet --use-mirrors
  - python setup.py --quiet install
notifications:
  email: false
  irc: "irc.freenode.org#XelNext"

