language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
env:
  - DJANGO_VERSION=1.3.7
  - DJANGO_VERSION=1.4.16
  - DJANGO_VERSION=1.5.11
  - DJANGO_VERSION=1.6.8
  - DJANGO_VERSION=1.7.1
matrix:
    exclude:
        - python: 2.6
          env: DJANGO_VERSION=1.7.1
        - python: 3.3
          env: DJANGO_VERSION=1.4.16
        - python: 3.3
          env: DJANGO_VERSION=1.3.7
        - python: 3.4
          env: DJANGO_VERSION=1.4.16
        - python: 3.4
          env: DJANGO_VERSION=1.3.7
script: "python manage.py test batchform"
install:
  - if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then pip install unittest2 --use-mirrors; fi
  - pip install Django==$DJANGO_VERSION --quiet --use-mirrors
  - python setup.py --quiet install
notifications:
  email: false
  irc: "irc.freenode.org#XelNext"

